spring:
  application:
    name: onehada
  neo4j:
    uri: neo4j+s://ad7123be.databases.neo4j.io
    authentication:
      username: neo4j
      password: Rf-LERPmTM9UmAR2HEoxm9jr2RJKPAZMxMCzjIYD1fk

  datasource:
    #    # serverDB
    #    url: jdbc:mysql://ajoufinance.iptime.org:3306/ONEHADA_serverDB
    #    username: Trolli
    #    password: Hanaro0526!
    #    driver-class-name: com.mysql.cj.jdbc.Driver
    # local testDB
    url: jdbc:mysql://localhost:3306/ONEHADA_localDB
    username: Trolli
    password: Trolli1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    generate-ddl: true

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 2000ms
    mongodb:
      #      uri: "mongodb://localhost:27017/User"

      uri: "mongodb+srv://rkdgml3577:rkdgml1234@onehada.vxoq0.mongodb.net/User?retryWrites=true&w=majority"

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # 최소 256비트 (32바이트) 이상
  access:
    token:
      expiration: 3600000 # 1시간
  refresh:
    token:
      expiration: 604800000 # 7일

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
