spring:
  application:
    name: onehada

  datasource:
    # H2 임베디드 데이터베이스 설정
    #    url: jdbc:h2:mem:testdb
    #    driver-class-name: org.h2.Driver
    #    username: sa
    #    password:
    # MySQL 설정
    url: jdbc:mysql://localhost:3306/ONEHADA_serverDB
    username: Trolli
    password: Trolli1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  # MongoDB 설정
  # mongodb:
  #   uri: mongodb://localhost:27017/your_database_name

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 2000ms

jwt:
  secret: Trolli1!
  access:
    token:
      expiration: 3600000
  refresh:
    token:
      expiration: 604800000

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
