spring:
  application:
    name: onehada

  datasource:
    # H2 임베디드 데이터베이스 설정
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    # MySQL 설정
    # url: jdbc:mysql://localhost:3306/your_database_name
    # username: your_username
    # password: your_password
    # driver-class-name: com.mysql.cj.jdbc.Driver

  # MongoDB 설정
  # mongodb:
  #   uri: mongodb://localhost:27017/your_database_name

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG  # 필요에 따라 로그 레벨 조정
