spring:
  application:
    name: onehada

  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 2000
      database: 0
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 2000ms

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # 최소 256비트 (32바이트) 이상
  access:
    token:
      expiration: 3600000  # 1시간
  refresh:
    token:
      expiration: 604800000  # 7일

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
