name: CI/CD Pipeline for ONEHADA_BE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  # 빌드 작업
  build:
    runs-on: ubuntu-latest

    steps:
      # 깃허브 리포지토리에서 소스 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle wrapper 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 환경변수 설정 (application.yml 작성)
      - name: Set application.yml for environment
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      # Gradle 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 빌드된 아티팩트 업로드
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: onehada-be
          path: build/libs/onehada-0.0.1-SNAPSHOT.jar

  # 배포 작업
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 빌드된 아티팩트 다운로드
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: onehada-be
          path: .

      # 다운로드된 파일 확인
      - name: List files
        run: ls -la

      # 기존 프로세스 종료 및 디렉토리 준비
      - name: Prepare deployment
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 프로젝트 디렉토리로 이동
            cd /home/${{ secrets.EC2_USERNAME }} || exit 1

            # Git 리포지토리 클론 (리포지토리가 없다면)
            if [ ! -d "ONE-HADA-BE/.git" ]; then
              git clone https://github.com/Hanaro-Trolly/ONE-HADA-BE.git
            fi

            cd ONE-HADA-BE || exit 1

            # 최신 코드 가져오기
            git fetch origin || exit 1
            git reset --hard origin/master || exit 1

            # 환경변수 설정
            cd ./src/main/resources || exit 1
            echo "${{ secrets.APPLICATION_YML }}" > application.yml || exit 1
            cd ../../.. || exit 1

            # Gradle 빌드 (테스트 제외)
            ./gradlew clean build -x test || exit 1

            # 애플리케이션 실행
            # 이전에 실행 중인 프로세스 종료 (정확한 프로세스를 종료)
            PID=$(pgrep -f 'java -jar build/libs/onehada-be-*.jar')
            if [ -n "$PID" ]; then
              kill -9 $PID
            fi

            # 새로운 애플리케이션 실행 (nohup 로그 추가)
            nohup java -jar build/libs/onehada-be-*.jar > /home/${{ secrets.EC2_USERNAME }}/app.log 2>&1 & || exit 1

            # 애플리케이션 실행 확인 (10초 대기 후 확인)
            sleep 10
            ps aux | grep 'java -jar' || exit 1

            exit 0
