name: CI/CD Pipeline for ONEHADA_BE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  # 빌드 작업
  build:
    runs-on: ubuntu-latest

    steps:
      # 깃허브 리포지토리에서 소스 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle wrapper 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

<<<<<<< HEAD
      # 환경변수 설정 (application.yml 작성)
      - name: Set application.yml for environment
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

=======
>>>>>>> 5415ab4 (chore : ci-cd.yml 완전 재건축)
      # Gradle 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 빌드된 아티팩트 업로드
      - name: Upload build artifact
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/upload-artifact@v3
        with:
<<<<<<< HEAD
<<<<<<< HEAD
          name: onehada-be
          path: build/libs/onehada-0.0.1-SNAPSHOT.jar
=======
        uses: actions/upload-artifact@v2
=======
        uses: actions/upload-artifact@v3
>>>>>>> 0f011b5 (chore: ci-cd.yml upload-artifact@ 한번 더 수정)
        with:
          name: onehada-be
          path: build/libs/onehada-be-*.jar
>>>>>>> 5415ab4 (chore : ci-cd.yml 완전 재건축)
=======
          name: onehada-be # 동일한 이름으로 업로드
<<<<<<< HEAD
          path: build/libs/onehada-be-*.jar # 올바른 경로로 설정
>>>>>>> a8532fd (chore: ci-cd.yml 또 수정)
=======
          path: build/libs/onehada*.jar # 올바른 경로로 설정
>>>>>>> 7fdd4ef (chore: 빌드파일명 수정)
=======
          name: onehada-be
          path: build/libs/onehada-0.0.1-SNAPSHOT.jar
>>>>>>> b523ad0 (chore: ci-cd.yml 뭔가 될것같은 커밋)

  # 배포 작업
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 빌드된 아티팩트 다운로드
      - name: Download build artifact
<<<<<<< HEAD
<<<<<<< HEAD
        uses: actions/download-artifact@v3
        with:
<<<<<<< HEAD
<<<<<<< HEAD
          name: onehada-be
          path: .

      # 다운로드된 파일 확인
      - name: List files
        run: ls -la

      # 기존 프로세스 종료 및 디렉토리 준비
      - name: Prepare deployment
=======
        uses: actions/download-artifact@v2
=======
        uses: actions/download-artifact@v3
>>>>>>> 2580f84 (chore: ci-cd.yml upload-artifact@v3 버전 수정)
        with:
          name: onehada-be
=======
          name: onehada-be # 업로드된 아티팩트 이름과 동일하게 설정
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> a8532fd (chore: ci-cd.yml 또 수정)
          path: build/libs/
=======
          path: build/libs/onehada-be-*.jar
>>>>>>> 59569d7 (chore: 작은 수정)
=======
          path: build/libs/onehada*.jar
>>>>>>> 7fdd4ef (chore: 빌드파일명 수정)
=======
          name: onehada-be
          path: build/libs/
>>>>>>> b523ad0 (chore: ci-cd.yml 뭔가 될것같은 커밋)

      # EC2에 배포
      - name: Deploy to EC2
>>>>>>> 5415ab4 (chore : ci-cd.yml 완전 재건축)
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # 프로젝트 디렉토리로 이동
            cd /home/${{ secrets.EC2_USERNAME }} || exit 1

            # 최신 코드 가져오기 (git pull로 최적화)
            if [ ! -d "ONE-HADA-BE/.git" ]; then
              git clone https://github.com/Hanaro-Trolly/ONE-HADA-BE.git || exit 1
            fi
            cd ONE-HADA-BE || exit 1
            git pull origin master || exit 1

            # 환경변수 설정
            cd ./src/main/resources || exit 1
            echo "${{ secrets.APPLICATION_YML }}" > application.yml || exit 1
            cd ../../.. || exit 1

            # 이전에 실행 중인 프로세스 종료 (정확한 프로세스를 종료)
            PID=$(pgrep -f 'java -jar build/libs/onehada-0.0.1-SNAPSHOT.jar')
            if [ -n "$PID" ]; then
              echo "Killing existing Java process with PID: $PID"
              kill -9 $PID || exit 1
            fi

<<<<<<< HEAD
            # 새로운 애플리케이션 실행 (nohup 로그 추가)
<<<<<<< HEAD
            nohup java -jar build/libs/onehada-be-*.jar > /home/${{ secrets.EC2_USERNAME }}/app.log 2>&1 & || exit 1
=======
            nohup java -jar build/libs/onehada*.jar > /home/${{ secrets.EC2_USERNAME }}/app.log 2>&1 &
>>>>>>> 1c01e74 (chore: 빌드파일명 한번 더 수정)
=======
            # 새로운 애플리케이션 실행 (포그라운드 실행)
            java -jar build/libs/onehada-0.0.1-SNAPSHOT.jar
>>>>>>> b523ad0 (chore: ci-cd.yml 뭔가 될것같은 커밋)

<<<<<<< HEAD
            # 애플리케이션 실행 확인 (10초 대기 후 확인)
            sleep 10
<<<<<<< HEAD
            ps aux | grep 'java -jar' || exit 1

=======
            if ! ps aux | grep -q '[j]ava -jar build/libs/onehada-be-*.jar'; then
              echo "Application failed to start" && exit 1
            fi

            echo "Deployment successful"
>>>>>>> 5415ab4 (chore : ci-cd.yml 완전 재건축)
=======
>>>>>>> 2580f84 (chore: ci-cd.yml upload-artifact@v3 버전 수정)
            exit 0
