name: CI/CD Pipeline for ONEHADA_BE

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

permissions:
  contents: read

jobs:
  # 빌드 작업
  build:
    runs-on: ubuntu-latest

    steps:
      # 깃허브 리포지토리에서 소스 코드 체크아웃
      - name: Checkout Code
        uses: actions/checkout@v3

      # JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Gradle wrapper 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 환경변수 설정 (application.yml 작성)
      - name: Set application.yml for environment
        run: |
          echo "${{ secrets.APPLICATION_YML }}" > src/main/resources/application.yml

      # Gradle 빌드 (테스트 제외)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # 빌드된 아티팩트 업로드
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: onehada-be
          path: build/libs/onehada-0.0.1-SNAPSHOT.jar

  # 배포 작업
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 빌드된 아티팩트 다운로드 (CI 서버에서 다운로드)
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: onehada-be
          path: /tmp/onehada-be/

      # EC2에 배포
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # EC2 서버로 배포 디렉토리 이동
            cd /home/${{ secrets.EC2_USERNAME }}/ONE-HADA-BE || exit 1

            # 기존에 실행 중인 Java 프로세스 종료
            pkill -f 'java -jar' || true

            # 아티팩트를 EC2로 복사
            scp /tmp/onehada-be/onehada-0.0.1-SNAPSHOT.jar ${EC2_USERNAME}@${EC2_HOST}:/home/${{ secrets.EC2_USERNAME }}/ONE-HADA-BE/build/libs/ || exit 1

            # 새로운 애플리케이션 실행 (nohup으로 백그라운드 실행)
            nohup java -jar /home/${{ secrets.EC2_USERNAME }}/ONE-HADA-BE/build/libs/onehada-0.0.1-SNAPSHOT.jar > /home/${{ secrets.EC2_USERNAME }}/app.log 2>&1 &

            exit 0
